name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select test type to run'
        required: true
        default: 'web'
        type: choice
        options: 
          - web
          - api
        
jobs:
  test:
    
    runs-on: ubuntu-latest 
    steps:

    - name: Checkout branch 'main'
      uses: actions/checkout@v4

    - name: setup NodeJS
      uses: actions/setup-node@v4
      with:
        # node-version: lts/*
        node-version: '20'

    - name: Install dependencies
      run: npm ci
    
    - name: Cache playwright binaries
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright Browsers
      if: steps.cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Create .env file
      env:
        ENV_TEMPLATE: |
          EMAIL=$DB_EMAIL
          PASSWORD=$DB_PASSWORD
      run: |
        echo "$ENV_TEMPLATE" > .env
        sed -i "s|\$DB_EMAIL|${{ secrets.DB_EMAIL }}|g" .env
        sed -i "s|\$DB_PASSWORD|${{ secrets.DB_PASSWORD }}|g" .env  

    - name: Run Playwright tests
      id : playwright_test
      run: |
        start=$(date +%s)
        npx playwright test --project=${{ github.event.inputs.test_type }}
        end=$(date +%s)
        DURATION=$(echo "$end - $start" | bc)
        FORMATTED_DURATION=$(date -u -d @${DURATION} +"%H:%M:%S")
        echo "duration=$FORMATTED_DURATION" >> $GITHUB_OUTPUT

    - name: Upload HTML test report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Determine payload slack notification
      id: slack_payload
      run: |        
        if [ "${{ job.status }}" == "success" ]; then
          PAYLOAD='.github/actions/slack/test-summary-success.json'
        else
          PAYLOAD='.github/actions/slack/test-summary-failed.json'
        fi
        echo "payload=$PAYLOAD" >> $GITHUB_OUTPUT

    - name: trigger slack notification
      uses: slackapi/slack-github-action@v2.1.0
      with:
        payload-file-path: ${{ steps.slack_payload.outputs.payload }}
        payload-templated: true
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
      env :
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }},
        SLACK_DURATION: ${{ steps.playwright_test.outputs.duration }}
        SLACK_BUILD_NUMBER: ${{ github.run_number }}
        GITHUB_URL_BUILD: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" 
        GITHUB_BRANCH: ${{ github.ref_name }}
        GITHUB_TEST_TYPE: ${{ github.event.inputs.test_type }}
        
