name: Playwright Tests
on:
  workflow_dispatch:
jobs:
  test:
    
    runs-on: ubuntu-latest 
    steps:

    - name: Checkout branch 'main'
      uses: actions/checkout@v4

    - name: setup NodeJS
      uses: actions/setup-node@v4
      with:
        # node-version: lts/*
        node-version: '20'

    - name: Cache playwright binaries
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/lockfiles') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Install Playwright Browsers
      if: steps.cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload HTML test report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7
