name: Slack notification test
on:
    workflow_dispatch:

jobs:
    begin:
        runs-on: ubuntu-latest 
        steps:

        - name: trigger slack notification
          uses:  slackapi/slack-github-action@v2.1.0
          with:
            payload-file-path: "/.github/actions/slack/slack-test-summary.json"
            payload-templated: true
            webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
            webhook-type: incoming-webhook
        env :
            SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}