name: Slack notification test
on:
    workflow_dispatch:
        inputs:
            test_type:
                description: 'Select test type to run'
                required: true
                type: string
jobs:
    begin:
        runs-on: ubuntu-latest 
        steps:
        - name: Checkout the repo
          uses: actions/checkout@v4
          with:
            persist-credentials: false

        - name: trigger slack notification
          uses:  slackapi/slack-github-action@v2.1.0
          with:
            payload-file-path: ${{ github.event.inputs.test_type }}
            payload-templated: true
            webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
            webhook-type: incoming-webhook
        env :
            SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}