name: Slack notification test
on:
    workflow_dispatch:
       inputs:
        test_type:
            description: 'Select notification type'
            required: true
            default: 'success-notification'
            type: choice
            options: 
            - success-notification
            - fail-notification
jobs:
    begin:
        runs-on: ubuntu-latest 
        steps:
        - name: Checkout the repo
          uses: actions/checkout@v4
          with:
            persist-credentials: false

        - name: Determine payload slack notification
          id: slack_payload
          run: |
            start=$(date +%s)
            if [ "${{ github.event.inputs.test_type }}" == "success-notification" ]; then
              PAYLOAD='.github/actions/slack/test-summary-success.json'
            else
              PAYLOAD='.github/actions/slack/test-summary-failed.json'
            fi
            end=$(date +%s)
            DURATION=$(echo "$end - $start" | bc)
            FORMATTED_DURATION=$(date -u -d @${DURATION} +"%H:%M:%S")
            echo "payload=$PAYLOAD" >> $GITHUB_OUTPUT
            echo "duration=$FORMATTED_DURATION" >> $GITHUB_OUTPUT

        - name: trigger slack notification
          uses: slackapi/slack-github-action@v2.1.0
          with:
            payload-file-path: ${{ steps.slack_payload.outputs.payload }}
            payload-templated: true
            webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
            webhook-type: incoming-webhook
          env :
            SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }},
            SLACK_DURATION: ${{ steps.slack_payload.outputs.duration }}
            SLACK_BUILD_NUMBER: ${{ github.run_number }}
            GITHUB_URL_BUILD: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" 